name: MenuAPI
version: '1.0-SNAPSHOT'
main: net.zypr.menuAPI.MenuAPI
api-version: '1.21'
authors: [ ZyprA ]
description: ImgTrail is a plugin that player can portray of their own trail.

commands:
  test:
    description: test
    usage: /test
    aliases: [ t ]